[env]
friendbot = "https://friendbot-futurenet.stellar.org/"
network = "futurenet"

[env.futurenet]
friendbot = "https://friendbot-futurenet.stellar.org/"
network = "futurenet"

[env.standalone]
friendbot = "http://localhost:8000/friendbot"
network = "standalone"

[tasks.run_standalone_server]
script = '''
  docker run --rm -it \
    -p 8000:8000 \
    --name stellar \
    stellar/quickstart:soroban-dev@sha256:a6b03cf6b0433c99f2f799b719f0faadbb79684b1b763e7674ba749fb0f648ee \
    --standalone \
    --enable-soroban-rpc
'''

[tasks.create_account_admin]
script = '''
  soroban config identity generate admin
  curl "${friendbot}?addr=$(soroban config identity address admin)"
'''

[tasks.create_account_players]
script = '''
  for PLAYER in 1 2 3
  do
    soroban config identity generate player_$PLAYER
    curl "${friendbot}?addr=$(soroban config identity address player_$PLAYER)"
  done
'''

[tasks.accounts]
dependencies = [
  "create_account_admin",
  "create_account_players"
]

[tasks.deploy]
script = '''
  soroban contract deploy \
  --source admin \
  --wasm ../../target/wasm32-unknown-unknown/release/raffle.wasm \
  --network ${network} > /tmp/contract_id.txt
'''

[tasks.token]
script = '''
  soroban lab token id --asset native --network ${network} > /tmp/token_id.txt
'''

[tasks.invoke_init]
script = '''
  soroban contract invoke \
  --id $(cat /tmp/contract_id.txt) \
  --source admin \
  --network ${network} \
  -- \
  init \
  --admin $(soroban config identity address admin) \
  --token $(cat /tmp/token_id.txt) \
  --max_winners_count 1 \
  --ticket_price 5001
'''

[tasks.invoke_buy_tickets]
script = '''
  for PLAYER in 1 2 3
  do
    soroban contract invoke \
    --id $(cat /tmp/contract_id.txt) \
    --source player_$PLAYER \
    --network ${network} \
    -- \
    buy_ticket \
    --by $(soroban config identity address player_$PLAYER)
  done
'''

[tasks.invoke_play_raffle]
script = '''
  soroban contract invoke \
  --id $(cat /tmp/contract_id.txt) \
  --source admin \
  --network ${network} \
  -- \
  play_raffle \
  --random_seed 1234
'''

