[package]
name = "voting"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.9.2"

[dev-dependencies]
soroban-sdk = { version = "0.9.2", features = ["testutils"] }
rstest = "0.17.0"
