[env]
friendbot = "https://friendbot-futurenet.stellar.org/"
network = "futurenet"

[env.futurenet]
friendbot = "https://friendbot-futurenet.stellar.org/"
network = "futurenet"

[env.standalone]
friendbot = "http://localhost:8000/friendbot"
network = "standalone"

[tasks.run_standalone_server]
script = '''
  docker run --rm -it \
    -p 8000:8000 \
    --name stellar \
    stellar/quickstart:soroban-dev@sha256:a6b03cf6b0433c99f2f799b719f0faadbb79684b1b763e7674ba749fb0f648ee \
    --standalone \
    --enable-soroban-rpc
'''

[tasks.create_account_admin]
script = '''
  soroban config identity generate admin
  curl "${friendbot}?addr=$(soroban config identity address admin)"
'''

[tasks.create_account_players]
script = '''
  for PLAYER in 1 2 3
  do
    soroban config identity generate player_$PLAYER
    curl "${friendbot}?addr=$(soroban config identity address player_$PLAYER)"
  done
'''

[tasks.accounts]
dependencies = [
  "create_account_admin",
  "create_account_players"
]

[tasks.deploy]
script = '''
  soroban contract deploy \
  --source admin \
  --wasm ../../target/wasm32-unknown-unknown/release/voting.wasm \
  --network ${network} > /tmp/contract_id.txt
'''

[tasks.invoke_init]
script = '''
  soroban contract invoke \
  --id $(cat /tmp/contract_id.txt) \
  --source admin \
  --network ${network} \
  -- \
  init \
  --admin $(soroban config identity address admin) \
  --voting_period_secs 3600 \
  --target_approval_rate_bps 50000 \
  --total_voters 3
'''

[tasks.invoke_create_proposal]
script = '''
  soroban contract invoke \
  --id $(cat /tmp/contract_id.txt) \
  --source admin \
  --network ${network} \
  -- \
  create_proposal \
  --id 1
'''

[tasks.invoke_vote]
script = '''
  for PLAYER in 1 2 3
  do
    soroban contract invoke \
    --id $(cat /tmp/contract_id.txt) \
    --source player_$PLAYER \
    --network ${network} \
    -- \
    vote \
    --voter $(soroban config identity address player_$PLAYER) \
    --id 1
  done
'''

